### ISSUE TITLE
macOS 14-15: AttributeGraph/Attribute.swift:473: Fatal error: attempting to create attribute with no subgraph: WindowToolbarStyleEnvironment

### ISSUE THREAD

**Issue by gabefletch** [ronitsingh10/FineTune#54]
Related to Issue #39 

On v1.0.0, it was found that opening the app on macOS 14 or 15 would result in the following error, visible by manually running the Unix Executable for the app via Show Package Contents > Contents > MacOS > FineTune
```
AttributeGraph/Attribute.swift:473: Fatal error: attempting to create attribute with no subgraph: 
WindowToolbarStyleEnvironment
zsh: trace trap /Applications/FineTune.app/Contents/MacOS/FineTune
```
The issue hasn't been able to be reproduced on macOS 26, where it opens as intended.

Now that v1.1.0 has been released, it would be helpful if someone could attempt to see if this behavior still happens on macOS versions prior to 26. I can't do this myself anymore since I upgraded to 26 shortly after commenting on Issue #39 and only own a single device that runs macOS.

**Comment by whitestrake** [comment]
Still seeing this issue:

```
whitestrake at ~
❯ sw_vers
ProductName:		macOS
ProductVersion:		14.2.1
BuildVersion:		23C71

whitestrake at ~
❯ brew info FineTune
==> finetune ✔: 1.2.0 (auto_updates)
https://github.com/ronitsingh10/FineTune
Installed
/opt/homebrew/Caskroom/finetune/1.2.0 (6.6MB)
  Installed using the formulae.brew.sh API on 2026-02-02 at 09:53:06
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/f/finetune.rb
==> Name
FineTune
==> Description
Per-application volume mixer, equalizer, and audio router
==> Artifacts
FineTune.app (App)
==> Analytics
install: 1,493 (30 days), 1,493 (90 days), 1,493 (365 days)

whitestrake at ~
❯ /opt/homebrew/Caskroom/FineTune/1.2.0/FineTune.app/Contents/MacOS/FineTune
AttributeGraph/Attribute.swift:473: Fatal error: attempting to create attribute with no subgraph: WindowToolbarStyleEnvironment
fish: Job 1, '/opt/homebrew/Caskroom/FineTune…' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

I have been majorly procrastinating on the MacOS upgrades...

**Comment by ronitsingh10** [comment]
As of v1.3.0, the minimum requirement is macOS 15.0 (Sequoia). The AttributeGraph crash was caused by SwiftUI framework incompatibilities on macOS 14. Since this cannot be fixed without dropping modern SwiftUI features, the minimum version has been raised. Closing as resolved by minimum version change.
