### ISSUE TITLE
AttributeGraph/Attribute.swift:473: Fatal error: attempting to create attribute with no subgraph: WindowToolbarStyleEnvironment

### ISSUE THREAD

**Issue by dawit909** [ronitsingh10/FineTune#39]
I downloaded the file using .dmg and nothing happened every time i double clicked finetune on applications. So i uninstalled it and downloaded via brew and it was same. Then I ran:
/Applications/FineTune.app/Contents/MacOS/FineTune

on my M1 air terminal and got:
AttributeGraph/Attribute.swift:473: Fatal error: attempting to create attribute with no subgraph: WindowToolbarStyleEnvironment
zsh: trace trap  /Applications/FineTune.app/Contents/MacOS/FineTune

My macOS version is 14.5.

**Comment by gabefletch** [comment]
I've got the same issue on an M1 MacBook Air running macOS 15.0, regardless of installing via .dmg or with Homebrew.

**Comment by dawit909** [comment]
Problem solved after updating to 26. But when downloading it specifically said MacOS 14 or later are compatible. That can be misleading.

**Comment by gabefletch** [comment]
Also confirming this issue doesn't occur on macOS 26, but I feel this issue should remain open since the intended behavior according to the README is for the app to support 14 and above as mentioned earlier.
